Repository comorment/containers, pull requests merged in 2022-11, with the labels that each got.

#82 Remove broken links to MiXeR usage scenarios
  usecases/README.md
Labels: documentation

#84 Add tests for `metal`, `qctool` in`gwas.sif`.
  CHANGELOG.md
  tests/extras/GlucoseExample.tar.gz
  tests/test_gwas.py
Labels: enhancement

#79 Strip container builds of source files etc.
  CHANGELOG.md
  src/README.md
  src/dockerfiles/gwas/Dockerfile
  src/dockerfiles/hello/Dockerfile
  src/dockerfiles/python3/Dockerfile
  src/dockerfiles/r/Dockerfile
  src/scripts/apt_get_essential.sh
  src/scripts/install_bolt.sh
  src/scripts/install_vcftools.sh
  tests/test_gwas.py
Labels: enhancement

#89 clean up install of htslib, bcftools, shapeit4
  src/README.md
  src/dockerfiles/gwas/Dockerfile
  src/scripts/install_bcftools.sh
  src/scripts/install_htslib.sh
  src/scripts/install_king.sh
  src/scripts/install_metal.sh
  src/scripts/install_shapeit4.sh
  src/scripts/patches/shapeit4.makefile.diff
Labels: enhancement

#93 LDPRED2 scripts for PRS analyses
  tests/ldpred2/build.sh
  tests/ldpred2/container.def
  tests/ldpred2/impute.R
  tests/ldpred2/ldpred2.R
  tests/ldpred2/run_ldpred2.sh
Labels: enhancement

#88 Add autogeneration of documentation using Sphinx
  .gitignore
  .readthedocs.yml
  CHANGELOG.md
  README.md
  docs/README.md
  reference/README.md
  sphinx-docs/source/Makefile
  sphinx-docs/source/conf.py
  sphinx-docs/source/environment.yml
  sphinx-docs/source/index.rst
  sphinx-docs/source/make.bat
  src/README.md
  usecases/README.md
  version/version.py
Labels: documentation, enhancement
