Repository comorment/containers, pull requests merged in 2024-03, with the labels that each got.

#239 Deprecate Saige
  CHANGELOG.md
  docker/Makefile
  docker/dockerfiles/saige/Dockerfile
  docs/singularity/README.md
  docs/singularity/saige.md
  scripts/gwas/gwas.py
  singularity/saige.sif
  sphinx-docs/source/docs/singularity/saige.md
  sphinx-docs/source/singularity/README.md
  sphinx-docs/source/usecases/saige_demo.md
  tests/test_gwas_py.py
  tests/test_saige.py
  usecases/README.md
  usecases/gwas_demo.md
  usecases/gwas_real.md
  usecases/saige_demo.md
  usecases/saige_out/.gitattributes
  usecases/saige_out/example_3chr_saige_out
  usecases/saige_out/out2.rda
  usecases/saige_out/out2.varianceRatio.txt
  usecases/saige_out/out2_30markers.SAIGE.results.txt
  usecases/saige_out/out_vcf.log
  usecases/saige_out/out_vcf.nosex
  usecases/saige_out/out_vcf.vcf
  usecases/saige_out/pheno_cov.txt
  usecases/saige_out/samples.txt
Labels: enhancement, bug-fix

#240 Documentation updates
  .github/pull_request_template.md
  CHANGELOG.md
  README.md
  RELEASES.md
  docs/singularity/gwas.md
  docs/singularity/hello.md
  sphinx-docs/source/conf.py
  sphinx-docs/source/index.rst
  sphinx-docs/source/singularity/README.md
  sphinx-docs/source/singularity/external.md
Labels: documentation, enhancement

#242 references
  CHANGELOG.md
  docs/singularity/python3.md
  docs/singularity/r.md
Labels: documentation

#243 citation stuff
  CHANGELOG.md
  README.md
  citation.cff
Labels: documentation
